import type { Metadata } from "next";
import "../globals.css";
import Footer from '@/components/Admin/Footer';
import Header from "@/components/Admin/Header";
import SideNavBar from "@/components/Admin/SideNavBar";


export const metadata: Metadata = {
  title: "Checkias Dashboard",
  description: "Generated by Checkias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        {/* Sidebar */}
        <SideNavBar />
        
        {/* Main Content Section (Dynamic Content Area) */}
        <div className="flex-1 flex flex-col">
          {/* Header */}
          <Header />
          
          {/* Main Content */}
          <main className="ml-48 p-6">{children}</main>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
