import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Home/Header";
import Footer from "@/components/Home/Footer";
export const metadata: Metadata = {
  title: "Checkias Dashboard",
  description: "Generated by Checkias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
