import type { Metadata } from "next";
import "./globals.css";
import Footer from '@/components/Footer';
import Header from "@/components/Header";
import SideNavBar from "@/components/SideNavBar";


export const metadata: Metadata = {
  title: "Checkias Dashboard",
  description: "Generated by Checkias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <SideNavBar/>
        {children}
      <Footer />
      </body>
    </html>
  );
}
