// layout.tsx
// import { JwtContextProvider } from './context/context'; // Named import
import './globals.css'; // Import global styles

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Wrapping the children components with JwtContextProvider */}
        {/* <JwtContextProvider> */}
          {children}
        {/* </JwtContextProvider> */}
      </body>
    </html>
  );
}
