import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Jobs/Header";
export const metadata: Metadata = {
  title: "Checkias Dashboard",
  description: "Generated by Checkias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
